name: WeatherMan
main: me.fromgate.weatherman.WeatherMan
version: 1.1.0
softdepend: [WorldEdit, WorldGuard]
author: fromgate, fromgate@gmail.com
commands:
   wm:
      aliases: [wm, wman]
      description: Main WeatherMan command
      usage: |
           /wm help
   wth:
      aliases: [localweather, lweather, lwth]
      description: Local wth control command
      usage: |
           /wth <player|region|biome|world> [{name} <rain|clear|remove>]